apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 059579790370.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 059579790370.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 3a95bbbb
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
